// ===================================================
// بيانات أكواد الاستعلام الائتماني - اعداد / فادي عادل
// ===================================================

const CREDIT_DATA = [
  // البنوك العامة
  { id: 1, name: "البنك المركزي المصري", code: "00990001RA", category: "بنك عام", categoryEn: "Public Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 2, name: "بنك الإسكندرية", code: "01000001PC", category: "بنك عام", categoryEn: "Public Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 3, name: "البنك الأهلي المصري", code: "02000001PC", category: "بنك عام", categoryEn: "Public Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 4, name: "بنك القاهرة", code: "03000001PC", category: "بنك عام", categoryEn: "Public Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 5, name: "بنك مصر", code: "04000001PC", category: "بنك عام", categoryEn: "Public Bank", source: "أكواد الاستعلام الائتماني 2025" },

  // البنوك المتخصصة
  { id: 6, name: "البنك العقاري المصري العربي", code: "77000001SB", category: "بنك متخصص", categoryEn: "Specialized Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 7, name: "بنك التنمية الصناعية المصري", code: "80000001SB", category: "بنك متخصص", categoryEn: "Specialized Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 8, name: "البنك الزراعي المصري", code: "82010001SB", category: "بنك متخصص", categoryEn: "Specialized Bank", source: "أكواد الاستعلام الائتماني 2025" },

  // البنوك التجارية
  { id: 9, name: "المصرف المتحد", code: "12800001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 10, name: "المصرف المتحد", code: "01280001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 11, name: "البنك التجاري الدولي - مصر", code: "13000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 12, name: "بنك بلوم - مصر", code: "14000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 13, name: "بنك الإمارات دبي الوطني", code: "15000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 14, name: "بنك قناة السويس", code: "17000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 15, name: "بنك عودة", code: "19000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 16, name: "البنك الأهلي المتحد", code: "20000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 17, name: "بنك فيصل الإسلامي (البنك الوطني للتنمية)", code: "23000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 18, name: "البنك الأهلي الكويتي (بيريوس)", code: "24000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 19, name: "مصرف أبو ظبي الإسلامي", code: "25000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 20, name: "مصرف أبو ظبي الإسلامي", code: "25010001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 21, name: "بنك البركة", code: "26000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 22, name: "بنك الكويت الوطني", code: "27000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 23, name: "بنك الاتحاد الوطني - مصر", code: "30000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 24, name: "البنك المصري الخليجي", code: "32000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 25, name: "بنك اتش اس بي سي - مصر", code: "33000001CB", category: "بنك تجاري", categoryEn: "Commercial Bank", source: "أكواد الاستعلام الائتماني 2025" },

  // البنوك الاستثمارية
  { id: 26, name: "التجاري وفا بنك ايجبت (باركليز)", code: "41000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 27, name: "بنك مصر ايران للتنمية", code: "42000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 28, name: "بنك الشركة المصرفية العربية الدولية", code: "43000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 29, name: "بنك كريدي اجريكول - مصر", code: "44000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 30, name: "بنك قطر الوطني الأهلي (سوسيتيه جنرال)", code: "45000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 31, name: "بنك الاستثمار العربي", code: "46000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 32, name: "بنك التعمير والإسكان", code: "47000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 33, name: "بنك المؤسسة العربية المصرفية", code: "49000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 34, name: "البنك المصري لتنمية الصادرات", code: "50000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 35, name: "البنك العربي الافريقي الدولي", code: "54000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 36, name: "بنك كريدي السويس فيرست", code: "56000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 37, name: "جمال ترست بنك", code: "58000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 38, name: "لويدز بنك بي ال سي", code: "60000001IB", category: "بنك استثماري", categoryEn: "Investment Bank", source: "أكواد الاستعلام الائتماني 2025" },

  // البنوك الأجنبية
  { id: 39, name: "ذي بنك اوف نوفا سكوشيا", code: "36000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 40, name: "البنك الوطني العماني", code: "37000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 41, name: "بنك المشرق", code: "38000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 42, name: "البنك العربي", code: "39000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 43, name: "بنك أبو ظبي الأول", code: "51000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 44, name: "ستي بنك ان ايه - مصر", code: "53000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 45, name: "البنك الأهلي اليوناني", code: "57000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 46, name: "البنك الأهلي الباكستاني", code: "64000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 47, name: "بنك صادرات ايران", code: "66000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 48, name: "بنك الشرق الأوسط المحدود", code: "69000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 49, name: "مصرف الرافدين", code: "73000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 50, name: "البنك السوداني المصري", code: "95380001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 51, name: "توماس كوك", code: "96000001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 52, name: "امريكان اكسبريس", code: "96010001FB", category: "بنك أجنبي", categoryEn: "Foreign Bank", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات التمويل متناهي الصغر والجمعيات
  { id: 53, name: "شركة تنمية / شركة سنده", code: "00010001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 54, name: "جمعية رجال أعمال وسيدات أعمال - جمعية تنمية المجتمع بسوهاج", code: "00020000MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 55, name: "جمعية سيدات أعمال اسكندرية (تحسين الصحة)", code: "00020001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 56, name: "الجمعية المصرية للتنمية والتمويل", code: "00020002MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 57, name: "جمعية رجال الأعمال والمستثمرين الدقهلية", code: "00020003MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 58, name: "كاش", code: "00020011MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 59, name: "كاش قديم قبل بلتون", code: "00020012MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 60, name: "وسيلة (اور كابيتال)", code: "00020013MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 61, name: "جمعية سيدات أعمال ومستثمرين اسيوط", code: "00020156MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 62, name: "الشركة المصرية الوطنية (لييد)", code: "00021006MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 63, name: "المؤسسة المصرية", code: "00021007MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 64, name: "مؤسسة أنا المصري", code: "00021021MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 65, name: "شباب مصر", code: "00021028MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 66, name: "جمعية رجال الأعمال والمستثمرين بالشرقية", code: "00021029MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 67, name: "شركة ريديك", code: "00021030MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 68, name: "جمعية رجال الأعمال والمستثمرين اسيوط", code: "00021032MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 69, name: "الجمعية المصرية للتنمية الشاملة", code: "00021040MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 70, name: "سان مارك", code: "00021054MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 71, name: "جمعية تحفيظ القرآن الكريم", code: "00021057MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 72, name: "جمعية حواء", code: "00021076MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 73, name: "باب رزق", code: "00021114MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 74, name: "شركة BEST", code: "MF00021119", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 75, name: "جمعية رجال الأعمال والمستثمرين نجع حمادي", code: "00021132MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 76, name: "جمعية الصم والبكم لذوي الاحتياجات الخاصة", code: "00021143MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 77, name: "الأولى", code: "00021174MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 78, name: "جمعية المحبة", code: "00021181MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 79, name: "جمعية رابطة المرأة بأسيوط", code: "00021188MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 80, name: "مؤسسة تنمية الأسرة المصرية", code: "00021206MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 81, name: "جمعية تنمية المجتمع ببا", code: "00021219MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 82, name: "جمعية بشاير الخير", code: "00021231MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 83, name: "مبادرة", code: "00021245MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 84, name: "جمعية سيدات الأعمال والمستثمرين اسيوط (كود جديد)", code: "00021256MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 85, name: "جمعية المرأة الريفية", code: "00021259MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 86, name: "الشؤون الاجتماعية", code: "00021264MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 87, name: "المؤسسة المصرية للتنمية والتوريدات (جمعية محروسة بسوهاج)", code: "00021306MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 88, name: "جمعية تنمية القدرات بقنا", code: "00021359MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 89, name: "جمعية كاريتاس", code: "00021373MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 90, name: "الجمعية الإقليمية للتنمية والمشروعات", code: "00021375MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 91, name: "جمعية الصعيد", code: "00021420MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 92, name: "جمعية التنمية والطفولة", code: "00021424MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 93, name: "عمال المحاجر", code: "00021553MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 94, name: "جمعية خالد فضل", code: "00021815MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 95, name: "ريفي", code: "00030001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 96, name: "تساهيل", code: "00040001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 97, name: "مؤسسة التضامن", code: "00050001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 98, name: "جمعية تنمية المشروعات الصغيرة ببورسعيد", code: "00060001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 99, name: "الهيئة القبطية الإنجيلية", code: "00070001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 100, name: "مؤسسة مصر الخير", code: "00090001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 101, name: "شركة سنده للتمويل متناهي الصغر", code: "00100001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 102, name: "شركة أمان", code: "00110001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 103, name: "تمويلي", code: "00120001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 104, name: "شركة فوري", code: "00130001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 105, name: "فيتاس مصر", code: "00140001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 106, name: "جمعية صغار الصناع", code: "00160001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 107, name: "الأهلي تمكين", code: "00180001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 108, name: "شركة بدايتي", code: "00190001MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 109, name: "كاش للمبالغ الجديدة", code: "00200000MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 110, name: "ارادة", code: "00121007MF", category: "تمويل متناهي الصغر", categoryEn: "Microfinance", source: "أكواد الاستعلام الائتماني 2025" },

  // هيئات ومؤسسات أخرى
  { id: 111, name: "الصندوق الاجتماعي للتنمية", code: "93000001NB", category: "هيئة ومؤسسة أخرى", categoryEn: "Other Institution", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 112, name: "المصرف العربي الدولي", code: "95400001NB", category: "هيئة ومؤسسة أخرى", categoryEn: "Other Institution", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 113, name: "بنك ناصر الاجتماعي", code: "95000001NB", category: "هيئة ومؤسسة أخرى", categoryEn: "Other Institution", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 114, name: "جهاز تنمية المشروعات المتوسطة", code: "00010001NB", category: "هيئة ومؤسسة أخرى", categoryEn: "Other Institution", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 115, name: "المصرف العربي الدولي", code: "94000001NB", category: "هيئة ومؤسسة أخرى", categoryEn: "Other Institution", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات الخدمات المالية غير المصرفية
  { id: 116, name: "شركة تشارتر للاستشارات المالية", code: "00030001FS", category: "خدمات مالية غير مصرفية", categoryEn: "Non-Banking Financial Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 117, name: "شركة القاهرة التخصيم", code: "00040000FS", category: "خدمات مالية غير مصرفية", categoryEn: "Non-Banking Financial Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 118, name: "فاليو لخدمات البيع بالتقسيط", code: "00050001FS", category: "خدمات مالية غير مصرفية", categoryEn: "Non-Banking Financial Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 119, name: "شركة رأس المال المخاطر", code: "00060002FS", category: "خدمات مالية غير مصرفية", categoryEn: "Non-Banking Financial Services", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات الائتمان والخدمات الاستهلاكية
  { id: 120, name: "بريمور انترناشيونال لخدمات الائتمان", code: "00010001CR", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 121, name: "مجموعة شركة هاباك", code: "00010001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 122, name: "الشركة العالمية المتحدة للتجارة", code: "00030001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 123, name: "الشركة الدولية للاستثمار والتجارة", code: "00040001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 124, name: "شركة يونيون جروب", code: "00050001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 125, name: "المجموعة المصرية للأنظمة الطبية", code: "00060001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 126, name: "شركة درايف", code: "00070001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 127, name: "شركة B-TECH", code: "RC00090001", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 128, name: "شركة راية", code: "00110001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 129, name: "رواج لتجارة السيارات", code: "00120001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 130, name: "شركة عفراء لتكنولوجيا الحاسبات", code: "00130001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 131, name: "شركة مصر الحجاز لمواد التعبئة ومنتجات البلاستيك", code: "00140001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 132, name: "الشركة المصرية لأنظمة التغليف", code: "00150001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 133, name: "بروسوفت لنظم المعلومات", code: "00160001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 134, name: "شركة سكاي ايجيبت للتوريد", code: "00190001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 135, name: "شركة غليونجي للتجارة", code: "00200001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 136, name: "شركة سكاي فايناس لتقسيط السيارات", code: "00210001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 137, name: "كونتاكت", code: "00230001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 138, name: "تقسيط شركة فاليو", code: "00290001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 139, name: "أمان أجهزة وسلع معمرة", code: "00320001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 140, name: "فاينانشال تكنولوجيز", code: "00350001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 141, name: "سهولة", code: "00400001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 142, name: "مشروعي", code: "00460001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 143, name: "شركة حالا للبيع بالتقسيط", code: "00580001RC", category: "ائتمان واستهلاك", categoryEn: "Credit & Consumer Services", source: "أكواد الاستعلام الائتماني 2025" },

  // التأمين
  { id: 144, name: "المصرية للتأمين التكافلي حياة", code: "00010001IC", category: "تأمين", categoryEn: "Insurance", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات المرافق
  { id: 145, name: "الشركة الوطنية للغاز", code: "00010001UC", category: "مرافق", categoryEn: "Utilities", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 146, name: "اورانج مصر للاتصالات", code: "00020001UC", category: "مرافق", categoryEn: "Utilities", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات التمويل العقاري
  { id: 147, name: "التعمير للتمويل العقاري الأولى", code: "98000001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 148, name: "المصرية للتمويل العقاري", code: "98010001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 149, name: "تمويل للتمويل العقاري", code: "98020001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 150, name: "تمويل الإمارات للتمويل العقاري", code: "98040001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 151, name: "التيسير للتمويل العقاري", code: "98050001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 152, name: "شركة بيت (العربي الأفريقي الدولي) للتمويل العقاري", code: "98060001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 153, name: "سكن للتمويل العقاري", code: "98070001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 154, name: "الأهلي المتحد للتمويل العقاري", code: "98080001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 155, name: "الأهلي للتمويل العقاري", code: "98090001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 156, name: "شركة المصريين للتمويل العقاري", code: "98100001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 157, name: "شركة كونتاكت للتمويل العقاري", code: "98120001MG", category: "تمويل عقاري", categoryEn: "Mortgage Finance", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات التأجير التمويلي
  { id: 158, name: "الشركة الدولية لتأجير التمويل", code: "98500001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 159, name: "شركة توشكى للتأجير العقاري", code: "98510001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 160, name: "شركة كوربلبيس للتأجير التمويلي", code: "98520001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 161, name: "شركة اوريكس مصر للتأجير التمويلي", code: "98530001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 162, name: "شركة التوفيق للتأجير التمويلي", code: "98540001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 163, name: "شركة أملاك للتمويل مصر", code: "98550001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 164, name: "شركة تكنوليس للتمويل التأجيري", code: "98560001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 165, name: "شركة بيربوس للتأجير التمويلي", code: "98570001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 166, name: "شركة المصريين للإنماء الاقتصادي", code: "98580001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 167, name: "شركة جي بي للتمويل التأجيري", code: "98590001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 168, name: "شركة بي ان بي باربيا الإمارات دبي الوطني للتأجير التمويلي", code: "98600001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 169, name: "شركة سوجيليس ايجيبت (كيو ان بي الأهلي) للتأجير التمويلي", code: "98610001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 170, name: "شركة اديليس للتأجير التمويلي", code: "98620001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 171, name: "شركة تمويل للتأجير التمويلي", code: "98630001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 172, name: "شركة جراند انفستمنت (ارتشر فايناس) للتأجير التمويلي", code: "98640001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 173, name: "شركة ايماك للتأجير التمويلي", code: "98650001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 174, name: "شركة بيت الخبرة للتنمية الاقتصادية", code: "98660001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 175, name: "شركة الأهلي للتأجير التمويلي", code: "98670001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 176, name: "شركة بلس للتأجير التمويلي", code: "98680001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 177, name: "المجموعة المالية هيرميس للتأجير", code: "98700001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 178, name: "شركة العربي الأفريقي الدولي للتأجير", code: "98710001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 179, name: "جلوبال ليس للتأجير التمويلي", code: "98720001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 180, name: "التعمير للتأجير التمويلي الأولى", code: "98740001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 181, name: "شركة إنماء للتأجير التمويلي", code: "98750001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 182, name: "يونايتد للتأجير التمويلي", code: "98760001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 183, name: "شركة بي ام للتأجير التمويلي", code: "98770001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 184, name: "شركة تنمية للتأجير التمويلي", code: "98780001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 185, name: "شركة كايرو للتأجير التمويلي", code: "98800001LF", category: "تأجير تمويلي", categoryEn: "Leasing", source: "أكواد الاستعلام الائتماني 2025" },

  // شركات الإسكان والتعمير
  { id: 186, name: "شركة مدينة نصر للإسكان والتعمير", code: "00010001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 187, name: "مجموعة عامر", code: "00020001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 188, name: "شركة اوراسكوم للإسكان والتعمير", code: "00040001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 189, name: "شركة بالم هيلز للتعمير", code: "00050001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 190, name: "شركة ايه اي سي فايناس التجارية", code: "00060001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 191, name: "مجموعة مطاوع جروب للاستثمار", code: "00070001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
  { id: 192, name: "الشركة الدولية للتنمية العقارية", code: "00080001HS", category: "إسكان وتعمير", categoryEn: "Housing & Construction", source: "أكواد الاستعلام الائتماني 2025" },
];

// Category colors mapping
const CATEGORY_COLORS = {
  "بنك عام": { bg: "#1a3a5c", accent: "#3b82f6", icon: "🏛️" },
  "بنك متخصص": { bg: "#1a3a5c", accent: "#6366f1", icon: "🏦" },
  "بنك تجاري": { bg: "#1a3a5c", accent: "#06b6d4", icon: "🏦" },
  "بنك استثماري": { bg: "#1a2a4a", accent: "#8b5cf6", icon: "💼" },
  "بنك أجنبي": { bg: "#1a2a4a", accent: "#ec4899", icon: "🌐" },
  "تمويل متناهي الصغر": { bg: "#1a3a2a", accent: "#10b981", icon: "🌱" },
  "هيئة ومؤسسة أخرى": { bg: "#2a2a1a", accent: "#f59e0b", icon: "🏢" },
  "خدمات مالية غير مصرفية": { bg: "#2a1a2a", accent: "#a855f7", icon: "📊" },
  "ائتمان واستهلاك": { bg: "#2a1a1a", accent: "#ef4444", icon: "🛒" },
  "تأمين": { bg: "#1a2a3a", accent: "#14b8a6", icon: "🛡️" },
  "مرافق": { bg: "#1a2a1a", accent: "#84cc16", icon: "⚡" },
  "تمويل عقاري": { bg: "#2a1a1a", accent: "#f97316", icon: "🏠" },
  "تأجير تمويلي": { bg: "#1a1a2a", accent: "#64748b", icon: "📋" },
  "إسكان وتعمير": { bg: "#1a2a1a", accent: "#22c55e", icon: "🏗️" },
};
